.PHONY: test
test:
	@echo "No tests yet"

.PHONY: run
run:
	@echo "Starting application..."
	bun dev

.PHONY: build
build:
	@echo "Nothing to build yet"

.PHONY: install
install:
	@echo "+ $@"
	bun ci

.PHONY: verify
verify:
	@echo "Verifying application"
	$(MAKE) test
